### ISSUE TITLE
Video playback stops after resuming from 1-2 minute pause

### ISSUE THREAD

**Issue by FiReiSFuN** [iBaa/PlexConnect#437]
Pausing and resuming works well unless the video has been paused for approx 1-2 minutes. The video will resume playing, but after a short period (30 seconds?) the video will stop and PlexConnect returns to the video menu page. At that point, playback of the video can be started again and resumed from where it stopped.

**Comment by rix1337** [comment]
Can confirm. Likely plexconnect fails to keep the connection to plex open long enough

**Comment by iBaa** [comment]
Does this happen for transcoded as well as direct-played files?
Did you check if PMS cancels the transcoder process? If you look at `application.js`, around line 355, it should keep PMS/transcoder working...

**Comment by FiReiSFuN** [comment]
So far I have only been playing files that require transcoding and haven't been paying attention to the PlexConnect console output on the server as I'm running it via systemd. I will test with a direct play file and also note the console output for when this happens with a transcoded file.

**Comment by FreakNL** [comment]
I have the exact same problem.

I don't use direct play, everything is transcoded. If I pause for more then a few minutes, playback continues after pressing play for a little while and then just crashes back to the movie info screen. 

I can continue where the movie crashed, so it's not a dealbreaker, but it's annoying at the least...

**Comment by zachthinks** [comment]
I've been having the same issue. A minute or so after starting a movie or tv show the video playback will stop on its own and return to the previous screen - just like if I had hit the stop button on my remote. I can immediately resume play and it plays fine without interruption after that.

**Comment by xela1** [comment]
+1 on this.

Either returns to the previous screen or stops as if it's buffering, but never buffers.

Will try forcing direct play either to see if it does the same, but it's been transcoding every time I've seen

**Comment by mcwoot** [comment]
I've also been having the same issue for a little while now. All of my files are transcoded. Unfortunately, I do not have any direct play files to test with.

You can find a PMS log below, filtered with all of the lines that contain the IP of my Apple TV. I started playing a file around 16:00 and paused it soon after. I resumed at 16:04 and it stopped sometime around 16:05.

My PMS version is 0.9.17.2, PlexConnect is 0.5-dev-110516 and they're running on Debian 8.5.


[pms_app_tv.txt](https://github.com/iBaa/PlexConnect/files/326532/pms_app_tv.txt)

**Comment by opswhisperer** [comment]
Any update on this issue?

**Comment by mcwoot** [comment]
I'm currently on PMS 1.1.4 and no longer seem to be having this issue. Can anyone else confirm?

**Comment by Asgardsurfer** [comment]
On PMS 1.1.4 and I am also noticing that the pause problem is fixed.

**Comment by FiReiSFuN** [comment]
I'm on 1.1.4.2757 and it still happens.

**Comment by almontef** [comment]
I am running PMS 1.2.4 and I see the same exact issues on direct play, direct stream, or transcoded content. I am also running the latest Plexconnect. I have had this issue for months now.  This only happens with Plexconnect as I can have other Plex clients pause items for days and resume without issue. I would be willing to provide logs and test to see if we can get to the bottom of this rather annoying issue.

**Comment by FiReiSFuN** [comment]
Same issue persists on PMS 1.2.7.2987... Anything I can do to help bring about a fix for this issue?

**Comment by almontef** [comment]
Still happening on 1.3.x version. I would also like to ask if there is anything that I can do to help bring about a fix for this issue?

**Comment by Swainoo** [comment]
This is happening for me too, i've doubt it'l be resolved anytime soon seeing as iBaa hasn't responded to anyone on here or the plex forums since august.

Here's to hoping, iBaa if you come back I can provide logs as this happens nearly all of the time when I pause for a few minutes then resume.

**Comment by jeroenj** [comment]
I can see the `ping` calls in the log that Ibaa describes in https://github.com/iBaa/PlexConnect/issues/437#issuecomment-207053248. However after 180 seconds Plex kills the transcode job: `Shutting down idle session .... (idle time is 180 seconds)`. PlexConnect keeps pinging after it has been killed.

What I noticed is that the ping calls get a `401` (Unauthorized) request status:

```
Request: [<ip>:<port> (Subnet)] GET /video/:/transcode/universal/ping?session=<id> (10 live) TLS GZIP Signed-in
Completed: [<ip>:<port>] 401 GET /video/:/transcode/universal/ping?session=<id> (10 live) TLS GZIP 0ms 338 bytes
```

This might be related to it. I'll look into it if I find some time.

**Comment by roidy** [comment]
>What I noticed is that the ping calls get a 401 (Unauthorized) request status:

That's because when the transcoder is pinged we forget to pass the plex token :(

Try the following application.js file:

[application.txt](https://github.com/iBaa/PlexConnect/files/741944/application.txt)

Just change the extension from txt to js

**Comment by jeroenj** [comment]
Indeed. Adding the token was what I was planning on doing. I was trying to find any API documation for those transcode API calls but I couldn't find any.

Do you know if there is any (API docs)?

I'll try to look into it this evening.

**Comment by roidy** [comment]
No API doc that I know of, just try the application.txt file I added to my post, I've made the necessary changes to add the token, just remember to rename the file from txt to .js.

**Comment by jeroenj** [comment]
@roidy it works as expected. I've also added it in the ping calls called from a timer. (see #460)

Tested it by pausing a video for ~10minutes. I could see in the Plex logs that it kept the transcoder alive. I've resumed playback for ~5minutes after pausing without any issues. (It used to stop after ~20seconds.)

Thanks a lot! :)

**Comment by Swainoo** [comment]
Is that application.js you posted universal for everyone to try?

I dropped in my PlexConnect-master/assets/js folder but i got the same result, i went to make some dinner for 20 minutes and left a program paused but after a few minutes it stop playing and requires me to resume playing like before.

**Comment by jeroenj** [comment]
It's based on the master branch. Were you using that or one of the (old) versioned releases?

I don't think it's needed but did you restart plexconnect after changing the application.js?

You can also check the Plex logs for the ping calls. If they return a 401 status it means that it didn't work.

Also: the application.js provides by @roidy is not yet complete. Check #460 for what works for me.

**Comment by roidy** [comment]
>Also: the application.js provides by @roidy is not yet complete. Check #460 for what works for me.

Yep, just a quick hack to see if that was the problem, I've merged your Pull, we'll see how it goes :)

**Comment by Swainoo** [comment]
So far so good, left something idle for 5 minutes and its been playing after resuming for another 5 minutes

Good job! This was my only issue with PlexConnect and it seems to be resolved.

**Comment by takerukoushirou** [comment]
Same for me, tried it several times over the last two days and haven't had any issue with pausing so far. Finally no more stop-and-play to pause-resume. Good job indeed!

**Comment by almontef** [comment]
After applying the latest Plexconnect update all was well with the pausing remaining in effect. However, I updated the plex server to the lastest plex pass version (1.4.3.3433) and the issue has come back. Anyone else running 1.4.3.3433 plex server and seeing the pause/resume issue with Plexconnect? Perhaps a new fix for those running the latest PMS is in order? Thanks in advance.

**Comment by almontef** [comment]
The issue is resolved as I forgot I restarted the PMS. Able to pause for long periods then resume with no problem.

**Comment by abetancort** [comment]
@roidy did it make it to master branch or we have to wait for further testing before merging it?

**Comment by roidy** [comment]
The changes were merged into the master branch on the 1st of Feb. A couple of people have reported back that it seems to fix the issue.

**Comment by moodyblue** [comment]
Does this problem still exists ?

**Comment by veremenko-y** [comment]
I still have the same/similar issue when resuming playback after computer entered sleep. I have to refresh the page.

**Comment by denis-itskovich** [comment]
Sill exists in 2023
