### ISSUE TITLE
no art on shows and movies

### ISSUE THREAD

**Issue by Jelly-Flinger** [iBaa/PlexConnect#602]
Hi,

Been running 0.7-dev-151218 on windows 10 and getting some issues with some missing art and plexconnect not working when I switched away from the legacy plex move/show matching.  

Decided to switch to go for the latest build (0.7.3) as it sounds like it would adress the issues. Based upon my reading it shsould be as simple as replacing the PlexConnect-master folder with a fresh unzip and copying across the certifcates from the original (now renamed ) install. 

Fires up ago but now I have no art! Turned on high level in the config files for error reporting but not seeing enything untoward. 

Plex (Version 4.57.4) console is throwing an occasional error about a missing plugin but dont think thats related. 

Any thoughts?

**Comment by moodyblue** [comment]
Is PlexConnect signed to plex.tv ? I'm also having this problem in such situation, but when I logout PlexConnect (which implies authorizing the network) it works ok.

I did not yet find how to solve this issue.

**Comment by moodyblue** [comment]
I've applied a temporary fix, can you pls test ? It's not published as a release, you have to download a zip from

https://github.com/iBaa/PlexConnect/archive/refs/heads/master.zip

**Comment by gunnahafta** [comment]
I had same problem.  Applies the temp fix and is working again.

**Comment by Jelly-Flinger** [comment]
Wow - fast response! Thankyou so much.

Tried the new file with same results (no art). However,  I also noticed files are not playing either. 

Dug around and noticed the shortcut I had in place was not working. I usuauly start plexconnect in a window rather than in the background. 

Looks like I had some issues with permissions so I changed a few and the shortcut started working. Is it possible I have some files/folder permission issues?

Check the .cfg files (as I remember fiddling around with these ages ago)

Settings.cfg is identical in my semi working 0.7 install

ATVsetting.cfg has some minor difference is streaming rates. However I noticed that below  [DY3N6WY8FF54] the new install has fanart =Hie and nothing else. Lots of other entries in my working install?

**Comment by moodyblue** [comment]
The problem with this temp fix is that it forces PlexConnect to use remote connections to access a local server. So it's not a good solution.. Normally PlexConnect should:
1) obtain the list of PMS servers from plex.tv
2) Servers have one (or more) IP:port for local access, and may have another IP:port for remote access
3) Test access through all IP:port reported by plex.tv
4) For servers accessible locally, PlexConnect decides to use a local IP:port
5) For remote servers PlexConnect decides to use a remote IP:port
The problem is that when PlexConnect decides to use a local IP:port the link with PMS is broken. It worked years ago and seems to still be working for some users. I have not been able to understand why.

My temporary fix "obliges" PlexConnect to not use local IP:ports but some users reported that the temporary fix does not work.

If PlexConnect is not logged to plex.tv it connects to the local server (requiring LAN authorization in PMS), and of course is unable to use remote servers (shared by others with us), and also unable to use other plex pass functions (sucha as multi user)

**Comment by moodyblue** [comment]
I think I have fixed it, can you pls test ?

https://github.com/iBaa/PlexConnect/archive/refs/heads/master.zip

**Comment by gunnahafta** [comment]
Looks good so far.

**Comment by moodyblue** [comment]
@gunnahafta thanks

@Jelly-Flinger what about you ?

**Comment by moodyblue** [comment]
@gunnahafta may I ask you to share one of your libraries with me (plex user moody_blue) ?

Let me explain why. One user in Plex forum is having this same problem but my fix doesn't work for him. He shared one library with me and I can't see any thumbnails os play media, so I would like to test with another user, such as you, for who the patch is ok.

**Comment by Jelly-Flinger** [comment]
Hi, still not working for me. No art but also fails to play back. 

Think I also accidentaly overwrote the configuration file in my working copy (left it open in an editor after rnaming files). That one has no art but does play back. 

I notice I keep getting folder permission issues when I copy in the new software versions so starting from a command prompt with administrator privelegs.

**Comment by moodyblue** [comment]
@Jelly-Flinger PlexConnect is an 'old' Plex client, therefore you can't use some security capabilities in recent PMS versions. Pls see explanation in https://forums.plex.tv/t/plexconnect-0-7-3-no-images-and-wont-see-pillow/720199/48?u=moody_blue

**Comment by Jelly-Flinger** [comment]
Will do!

Funnily enough I had found that thread 30 mins ago! Noticed the lack of Pil/Pillow in the settings and google lead me to it. Sounds very similar.

Will try and work through all the steps using the latest version, log out of plex tv etc and see what happens

**Comment by moodyblue** [comment]
Fixed in V0.7.4

**Comment by Jelly-Flinger** [comment]
Updated with 0.74 and worked straight away! Many thanks
